import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MiddleBar from "@/components/navbar/MiddleBar";
import Navbar from "@/components/navbar/Navbar";
import TopBar from "@/components/navbar/TopBar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TopBar/>
      <MiddleBar />
      <Navbar />
      <body className={inter.className}>{children}
        <Footer/>
      </body>
    </html>
  );
}
